### PR TITLE
Fix go-swagger/go-swagger#1796 (circular $ref with cycle in remote)

### PR DESCRIPTION
**Pull request by fredbi**
* contributes go-swagger/go-swagger#1796
* contributes go-swagger/go-swagger#1767
* contributes go-swagger/go-swagger#1774

Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

### CODE REVIEW

**Comment by fredbi** [comment]
Strange build failure with golangci:
```
ErrorFailed to load program with go/packages: go [list -e -json -compiled -test=true -export=false -deps=true -- ./...]: exit status 1: go build github.com/go-openapi/jsonpointer: no Go files in
go build github.com/go-openapi/spec: no Go files in
go build github.com/go-openapi/strfmt: no Go files in
go build github.com/go-openapi/swag: no Go files in
"
```

**Comment by kstedman9** [comment]
@fredbi  I pulled your changes locally and rebuilt my complete swagger.  It seems to fix the issues I was having with the flattening issue.  I will do more work on it this weekend to verify it.

**Comment by fredbi** [comment]
Reported golangci failure: https://github.com/golangci/golangci/issues/25

**Comment by fredbi** [comment]
Thanks @kstedman9! You also have a WIP PR on go-swagger which onboards this change and tests some similar issues.

**Pull request merged**
